kind: Service
apiVersion: v1
metadata:
  namespace: monitoring
  name: prometheus-svc
spec:
  selector:
    app: prometheus
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9090
